spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chess?serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 90000
      max-lifetime: 90000
      connection-timeout: 90000
      pool-name: DatebookHikariCP
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 7070